# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mOUmt22R8HsMqJ_D7pxI4-MQjgu4ucqz
"""

import pandas as pd
import numpy as np
import datetime as dt

class Words_Builder():
  def __init__(self):
    self.sentences = []
  
  def get_words(chat_path, highlights_path):
    chats = pd.read_csv('/content/gdrive/My Drive/761217067.csv')
    chats = np.array(data)
    start, end = self.highlight_open(highlights_path)
    i = 0

    for chat in chats:
      if chat[2] < start[i]:
        continue
      while chat[2] > end[i]:
        i += 1
        if i >= len(end):
          break
      if i >= len(end):
        break 
      if chat[2] >= start[i]:
        self.sentences.append(chat[1])

  def convert_seconds(string):
    string = list(map(int, string.split("’")))
    return 3600 * string[0] + 60 *string[1] + string[2]

  def highligt_open(path):
    file = open(path, 'r')
    string = file.readline()
    string = string.replace('[', '|')
    string = string.replace(']', '')
    string = string.replace(' ', '')
    temp = string.split('|')
    i = 0
    while i < len(temp):
      if temp[i] == '':
        del temp[i]
      else:
        i += 1
    start = []
    end = []
    for t in temp:
      t = t.split(',')
      start.append(self.convert_seconds(t[0]))
      end.append(self.convert_seconds(t[1]))
    return start, end

