# -*- coding: utf-8 -*-
"""words_builder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mOUmt22R8HsMqJ_D7pxI4-MQjgu4ucqz
"""

!pip install git+https://github.com/ssut/py-hanspell.git
!pip install soynlp
drive.mount('/content/gdrive/')
import pandas as pd
import numpy as np
from google.colab import drive 
from hanspell import spell_checker
from soynlp.normalizer import *

class Words_Builder():
  def __init__(self):
    self.words = []
  
  def get_words(chat_path, highlights_path):
    chats = pd.read_csv('/content/gdrive/My Drive/761217067.csv')
    chats = np.array(data)
    start, end = self.highlight_open(highlights_path)
    i = 0

    for chat in chats:
      if chat[2] < start[i]:
        continue
      while chat[2] > end[i]:
        i += 1
        if i >= len(end):
          break
      if i >= len(end):
        break 
      if chat[2] >= start[i]:
        #spelled_sent = spell_checker.check(chat[1])
        #hanspell_sent = spelled_sent.checked
        #words = hanspell_sent.split()
        words = chat[1].split()
        for w in words:
          w = self.preprocess(w)
          w = emoticon_normalize(w)
          if w not in self.words:
            self.words.update({w:1})
          else:
            self.words[w] += 1

  def convert_seconds(string):
    string = list(map(int, string.split("’")))
    return 3600 * string[0] + 60 *string[1] + string[2]

  def highligt_open(path):
    file = open(path, 'r')
    string = file.readline()
    string = string.replace('[', '|')
    string = string.replace(']', '')
    string = string.replace(' ', '')
    temp = string.split('|')
    i = 0
    while i < len(temp):
      if temp[i] == '':
        del temp[i]
      else:
        i += 1
    start = []
    end = []
    for t in temp:
      t = t.split(',')
      start.append(self.convert_seconds(t[0]))
      end.append(self.convert_seconds(t[1]))
    return start, end

  def preprocess(w):
    if w.find('ㄹㅇㅋㅋㅋ') != -1:
      w = 'ㄹㅇㅋㅋ'
    elif w.find('ㅋㅋㅋ') != -1 or  w.find('zz') != -1:
      w = 'ㅋㅋㅋ'
    elif w.find('오우') != -1 or  w.find('ㅗㅜㅑ') != -1 or w.find('퍄') != -1 or w.find('오오') != -1:
      w = '오'
    elif w.find('??') != -1:
      w = '?'
    elif w.find('깔끔') != -1:
      w = '깔끔'
    elif w.find('좋') != -1:
      w = '좋다'
    elif w.find('이게') != -1 or w.find('이게') != -1:
      w = '이걸'
    elif w.find('잘해') != -1 or w.find('잘했') != -1 or w.find('잘한') != -1 or w.find('잘하') != -1:
      w = '잘해'
    elif w.find('나이스') != -1:
      w = 'ㄴㅇㅅ'
    elif w.find('ㅅㅅ') != -1:
      w = 'ㅅㅅ'
    elif w.find('크') != -1 or w.find('캬') != -1 or w.find('키야') != -1:
      w = '크'
    elif w.find('패시브') != -1:
      w = '패시브'
    return w

